测试冲突：
  git did not exit cleanly (code 1)
